#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent
import secrets

data = json.load(sys.stdin)

# Setup default values
random_key = secrets.token_hex(16)
NEXTAUTH_SECRET = data.get("NEXTAUTH_SECRET",random_key)

# Talk with agent using file descriptor.

agent.set_env("PAPERLESS_SECRET_KEY", NEXTAUTH_SECRET)

NEXTAUTH_URL = data.get("NEXTAUTH_URL",random_key)
agent.set_env("NEXTAUTH_URL", NEXTAUTH_URL)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()