#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent
import secrets

data = json.load(sys.stdin)
#
# # DB Config
# POSTGRES_DB = data.get("POSTGRES_DB","linkwarden")
# POSTGRES_USER = data.get("POSTGRES_USER","linkwarden")
# POSTGRES_PASSWORD = data.get("POSTGRES_PASSWORD","LinkWard3n")
#
# db_config = {
#
#     "POSTGRES_ROOT_HOST": "localhost",
#     "POSTGRES_DATABASE": POSTGRES_DB,
#     "POSTGRES_USER": POSTGRES_USER,
#     "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
# }
# agent.write_envfile('database.env', db_config)

# Setup default values
random_key = secrets.token_hex(16)
NEXTAUTH_SECRET = data.get("NEXTAUTH_SECRET",random_key)

# Talk with agent using file descriptor.

agent.set_env("NEXTAUTH_SECRET", NEXTAUTH_SECRET)

NEXTAUTH_URL = data.get("NEXTAUTH_URL",data.get("TRAEFIK_HOST"))
agent.set_env("NEXTAUTH_URL", NEXTAUTH_URL+'/api/v1/auth')

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()